services:
  perkvector-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perkvector-api
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      USE_MOCK_MODE: "true"
    restart: unless-stopped
